name: |
  Title: Update | Asset: Build & Upload
on:  
  release:
    types: [published]
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
        - uses: actions/checkout@v3
        
        - name: Navigate to Workspace
          run: cd ${{ github.workspace }}
          
        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1

        - name: Tag Name replace 'v'
          uses: mad9000/actions-find-and-replace-string@4
          id: tagnameFR
          with:
            source: ${{ github.event.release.tag_name }}
            find: 'v'
            replace: ''

        - name: Set version of EGStealer equal to Tag name
          uses: secondbounce/assemblyinfo-update@v2
          with:
            version: ${{ steps.tagnameFR.outputs.value }}"
            directory: 'EGStealer/Properties'
            filename: 'AssemblyInfo.cs'
            recursive: false
        
        - name: Build Solution
          run: |
            msbuild EGStealer.sln -restore -p:RestorePackagesConfig=true -p:platform="Any CPU" -p:Configuration=Release

        - name: Upload Release Asset
          uses: softprops/action-gh-release@v1
          with:
            name: EGStealer ${{ github.event.release.tag_name }}
            prerelease: false
            files: |
              EGStealer/bin/Release/EGStealer.exe